### ISSUE TITLE
Error on tensor allocations (TFLite_Detection_PostProcess)

### ISSUE THREAD

**Issue by kad1r** [shaqian/tflite-react-native#16]
Hi,

I'm getting this error on loading model. First I used my trained tflite file, then I downloaded original tensorflow tflite example from website and it gives same error.
Not sure is it related with me but do you guys have any idea?

![image](https://user-images.githubusercontent.com/2114669/67521482-a471a180-f6b3-11e9-88de-81216e16e207.png)

**Comment by kad1r** [comment]
I assume this issue is related with how you convert your tflite file.
Some of tflite files are working well but some of them are not.

**Comment by shaqian** [comment]
Yes. It looks like something is wrong with the output tensor of the tflite file. Num of outputs is expected to be 4 but it's actually 1.

Thanks,
Qian
