### ISSUE TITLE
Error - 'tensorflow/lite/kernels/register.h' file not found

### ISSUE THREAD

**Issue by ombinar** [shaqian/tflite-react-native#19]
#include "tensorflow/lite/kernels/register.h"

Thanks.

**Comment by aleator83** [comment]
Hi,
had the same problem.

Using contrib path in node_modules/tflite-react-native/ios/TfliteReactNative.mm works for me.

You can either set ifdef to TRUE with

`sed -i '' 's/ifdef\ CONTRIB_PATH/ifdef\ TRUE/g' node_modules/tflite-react-native/ios/TfliteReactNative.mm`

or set CONTRIB_PATH for the TfliteReactNative project.

**Comment by shaqian** [comment]
Hi @ombinar,

@aleator83 is right. For early versions of tensorflow the header path is "tensorflow/contrib/lite/kernels".

You can uncomment `//#define CONTRIB_PATH` here to use the old path:
https://github.com/shaqian/tflite-react-native/blob/master/ios/TfliteReactNative.mm#L1

Thanks,
Qian

**Comment by A5mad** [comment]
In my case removing the "/contrib" from the path solved it for me
