### ISSUE TITLE
 Android: null is not an object evaluating TfliteReactNative.loadmodel

### ISSUE THREAD

**Issue by mdcroce** [shaqian/tflite-react-native#2]
Thanks for this project, it seems quite good.
I'm getting this issue when I try to run it on Android. Could you please help me?

Thanks!

**Comment by shaqian** [comment]
Hi, looks like the library is not linked to your project properly. Can you please try manually linking it? https://github.com/shaqian/tflite-react-native#android

**Comment by chirag773** [comment]
Hey I'm getting the same problem can you please help me `Could not invoke TfliteReactNative.loadModel 
null`

**Comment by chirag773** [comment]
> Hi, looks like the library is not linked to your project properly. Can you please try manually linking it? https://github.com/shaqian/tflite-react-native#android

I had done this manually but still I'm facing the same error

**Comment by techgig17** [comment]
I am facing the same error. Tried linking it manually too. Pls help as this is critical for the project

**Comment by xunaizhong20** [comment]
> Thanks for this project, it seems quite good.
> I'm getting this issue when I try to run it on Android. Could you please help me?
> 
> Thanks!

Android
In Android Studio (1.0 & above), right-click on the app folder and go to New > Folder > Assets Folder. Click Finish to create the assets folder.

Place the model and label files at app/src/main/assets.

In android/app/build.gradle, add the following setting in android block.

    aaptOptions {
        noCompress 'tflite'
    }

**Comment by LorandP** [comment]
I have the same issue and already added the resources to android but is still not working.
Also I have downloaded other two models from elsewhere and they are working fine and I have added them to android. 
So maybe the models that are not working are the problem?

**Comment by shaqian** [comment]
Hi, have you tried to launch the app in Android Studio? You will be able to get more verbose trace.

**Comment by LorandP** [comment]
Yes, I have tried and I get:
`Caused by: java.io.FileNotFoundException: models/model2.tflite`
But my model is in that directory, I don't understand why I get this.

**Comment by sgc445** [comment]
I have also faced same issue

**Comment by shaqian** [comment]
@LorandP @sgc445 
Please make sure you copied the `models` folder to `app/src/main/assets` and confirm it from Android Studio.

**Comment by sunilgc7** [comment]
Thanks, Solved my issue.

**Comment by alessandroraffa** [comment]
Same issue on iOS

> @LorandP @sgc445
> Please make sure you copied the `models` folder to `app/src/main/assets` and confirm it from Android Studio.

Where exactly should I put models for iOS?

Thanks in advance.

**Comment by RaviKiranMakala** [comment]
> Same issue on iOS
> 
> > @LorandP @sgc445
> > Please make sure you copied the `models` folder to `app/src/main/assets` and confirm it from Android Studio.
> 
> Where exactly should I put models for iOS?
> 
> Thanks in advance.

Any luck? I am able to run it on Android, but facing the issue with iOS. How would i add the models to iOS project exactly.
