### ISSUE TITLE
Access predicted probabilities for image classification

### ISSUE THREAD

**Issue by AlkaSaliss** [shaqian/tflite-react-native#9]
Hi
I've successfully tried your package using my own model for image classification case.
However as you pointed out in the README, the result is a single prediction : 
```json
{
  "index": 0,
  "label": "person",
  "confidence": 0.629
}
```

I would like to know where I should modify your code to get all predicted probabilities. e.g. something like this : 

```json
[
{
  "index": 0,
  "label": "person",
  "confidence": 0.6
},
{
  "index": 1,
  "label": "cat",
  "confidence": 0.3
}
{
  "index": 2,
  "label": "dog",
  "confidence": 0.1
}
]
```

Thanks in advance

**Comment by shaqian** [comment]
Hello,

The output is an array. Readme is not accurate. You can control the number of output by manipulating `numResults` but if the output won't be more than the actual outputs of the model prediction. 

Thanks,
Qian

**Comment by AlkaSaliss** [comment]
Thanks it finally worked

For whatever reason I was getting only an array with only one prediction as I was forgetting to divide the image by 255 (as this was the case when training the model.

Finally I got the array with the right number of predictions by just setting  imageStd to 255.0 in the runModelOnImage function.
